name: BowWars
version: '${project.version}'
main: mc.bowwars.BowWars
api-version: 1.18
authors: [ pleer__gr45 ]
description: Special plugin for Bow wars
commands:
  bowwarsplugin:
    description: bow wars main command
    usage: /bwp [ARGUMENTS] <--
    aliases: [bwp]
  bowwarspluginteam:
    description: bow wars team command
    usage: /bwpt [ARGUMENTS] <--
    aliases: [bwpt]
  teamselector:
    description: The command that causes the team selection
    usage: /bwpts [ARGUMENTS] <--
    aliases: [ bwpts ]
  bwpgens:
    description: The command installing generators
    usage: /bwpgens [ARGUMENTS] <--
    aliases: [ gens ]
  bwptrader:
    description: The command installing traders
    usage: /bwptrader [ARGUMENTS] <--
    aliases: [ trader ]
  bwptime:
    description: The command time
    usage: /bwptime [SECONDS] <-- 0 < x < 3600
    aliases: [ time ] 
